- hosts: all
  user: serveradmin
  become: true
  vars:
    docker_compose_version: "1.28.5"
  tasks:
    - name: create directories
      file:
       path: "{{ item }}"
       state: directory
       owner: "serveradmin"
       group: "serveradmin"
       mode: "u=rwx,g=rwx,o=rx,g+s" #make serveradmin user and group own the files and folders, 02 in the beginning corresponds to chmod g+s
      loop:
       - /home/serveradmin/docker/shared/DockerCompletedMovies
       - /home/serveradmin/docker/shared/DockerCompletedTVshows
       - /home/serveradmin/docker/shared/remotemovies
       - /home/serveradmin/docker/shared/remotekidsmovies
       - /home/serveradmin/docker/shared/remotetvshows
       - /home/serveradmin/docker/shared/remoteESXi
       - /home/serveradmin/docker/plex
       - /home/serveradmin/docker/sonarr
       - /home/serveradmin/docker/radarr
       - /home/serveradmin/docker/sabnzbd

